### ISSUE TITLE
Monu大写全角英文的一些问题

### ISSUE THREAD

**Issue by AmeroHan** [MY1L/QuQi#4]
1. 带有圆弧的字符视觉高度需要调整（如Ｍ、Ｎ的上部圆弧、Ｕ的下部圆弧与”竖“的视觉高度不平齐，Ｎ和Ｍ的视觉高度不一致）；
2. Ｓ比其他字符视觉高度大；
3. Ｓ、Ｕ、Ｎ等字母看上去是想努力占满字框，但Ｋ、Ｒ等字母并没有，建议统一一下处理方式。

**Comment by MY1L** [comment]
全角是故意设为与“半角”英文区别而且很丑，方便我在浏览时一眼区分别人“误用”的情况，并没有主动使用的价值。其原因是我没有免费软件去修改Montserrat alt源码。
不过，由于恰好存在竖排大写英文的需求，我需要原创与汉字视觉匹配、与Montserrat造型不同的多字重大写英数字体，那么做成后刚好可以拿来充当与“半角”英文区别的全角英文。大约未来2个月做。

**Comment by MY1L** [comment]
这段时间试作了一个竖排大写全角英文，只有常规字重，先放到字体里试试：[Monu~test.zip](https://github.com/MY1L/QuQi/files/6687544/Monu.test.zip)
看看如何，等形态确定了再做粗体。

**Comment by AmeroHan** [comment]
很多术语不知道，请见谅。

**好：**

1. 我很喜欢ＣＤＧＯ这些字母的字形。

**不好（？）**

2. 个人认为英文与中文视觉匹配并不意味着要和中文字面一样大，况且这个试作英文字面比中文还要大（主要是宽度，高度应该没什么问题）。
3. 弧形笔画的视觉修正似乎不足，看起来比平直笔画的字母要矮。
4. Ｂ、Ｐ、Ｒ的圆好尖啊
![image](https://user-images.githubusercontent.com/72120616/122797887-88902a00-d2f2-11eb-9cf3-4a62258b6606.png)
5. Ｊ是Ｄ改的？“竖”弯的好奇怪。  
6. Ｃ、Ｇ、Ｓ的切角是水平的，Ｊ、Ｑ的切角是倾斜的。
![image](https://user-images.githubusercontent.com/72120616/122789721-2fbc9380-d2ea-11eb-8382-713ec05d996d.png)

**或许不好（？）**

7. Ｘ、Ｙ、Ｋ的斜画末尾太尖了，有点扎眼。但似乎并没有不改变风格的解决办法。
8. 横排时Ｉ的短杠，可以考虑加长一下（纯个人理念）。

**Comment by MY1L** [comment]
- 所有弧的末笔切角是应该统一为垂直于弧的切线，所以把C、G、J都改了。S是恰好切在平行的地方不用改。Q应该像R末笔那样横切，但看着比较扎人，算了。
- 略微压窄了所有左右为平直笔画的字符宽度（实际上除了横平竖直的大多重画了一遍）
- 略微压扁了所有上下为平直笔画的字符高度（同上）
压了些尖锐的弧，这样方和圆视觉上面积应该比较接近。
- 呃我不知道怎么把Ｄ改成Ｊ。不过用意是差不多：直着向下看起来会向右翻倒似的，所以把头往中间拽一拽。

这个[Monu11.90.zip](https://github.com/MY1L/QuQi/files/6694360/Monu11.90.zip)版本追加了些应当在12版发布的字形，改善了键盘连字的按键符号和一些积累错误等。

**Comment by AmeroHan** [comment]
现在效果比较好了

**Comment by MY1L** [comment]
昨天做完了对应粗体：[綿雲飴里的动态-哔哩哔哩](https://t.bilibili.com/547536187682281448)，等有时间合并到Monu。

**Comment by MY1L** [comment]
刚做的另一个针对竖排大写英数需求的字体：https://github.com/MY1L/vert/releases/tag/4 这个用了可变字体的中粗部分。

**Comment by AmeroHan** [comment]
不想另开Issue了就在这说吧，这个全角英数的字面搭配微软雅黑还说得过去，但是搭配未来荧黑显得太大了。

**Comment by MY1L** [comment]
其实比汉字平均要窄……竖排使用上有没有其它问题？我在生成OT文件时感觉好像有什么毛病，系统总提示有损坏。

**Comment by AmeroHan** [comment]
Ai上竖排， `‼` `⁇` `⁈` `⁉` 方向相对理想状态逆时针旋转了90°；
Edge上竖排，中文标点符号的位置是错的，仍保持在左下角， `‼` `⁇` `⁈` `⁉` 方向相对理想状态逆时针旋转了90°。

也许是我不会用。

**Comment by MY1L** [comment]
不同软件支持不同，这个应该用vert特性解决，但某些软件不支持vert，还有某些软件一概横排，甚至`⸻`也横排，为了解决这些个我放了几个预应旋转的在私用区（https://github.com/MY1L/vert/releases/tag/3）
字面的话，高度应该没问题？我准备做成宽度可变字体把各种宽窄都试一遍，大约下个月左右搞。
Edge我就不懂了，旧系统没这个软件……

**Comment by AmeroHan** [comment]
高度没问题，但是字符向上挪动一点会更和谐。可以以“国”为参照。

**Comment by MY1L** [comment]
可变字体做好了，有字重和字宽2个轴，不过有些问题，所以直接生成了几种差别微妙的宽度，打算从这几个里取一个顺眼的当全角英文，请看看哪个字面比较合适：
[CtrlOrdn-wdth330~390.zip](https://github.com/MY1L/QuQi/files/6931858/CtrlOrdn-wdth330.390.zip)

> 基于 https://t.bilibili.com/548801038367849128?tab=2 投票结果，接下来我的完全原创字体系列命名为“Ctrl”。
> 而用于排行榜序数和竖排全角用的可变字体就叫“Ordn”（ordinal，OT序数特性）不过尴尬的是我这旧机子没有文字软件支持可变字体……
> 由于竖排用，字宽仅适用全角大写（等宽。A、V、W因为面积本来就小没有窄体）
> 小写部分赶时间用的小型大写凑数，不等宽，kern几乎没有。

**Comment by AmeroHan** [comment]
我觉得330最顺眼。不知道有没有更窄的

**Comment by MY1L** [comment]
有……但外观走形得比较难看了，目前的Ｏ形状还算比较超椭圆，但窄于330就变得有些站不住😅
Ctrl系列字体准备下周发布到： https://github.com/MY1L/Ctrl ，今天先发布了字体后缀缩写表“[abbr.md](https://github.com/MY1L/Ctrl/blob/main/abbr.md)”准备用于命名非可变字体，请看有没有问题或可补充的。

**Comment by AmeroHan** [comment]
可以给K、X、Y尖锐的部分加上小倒角，不过我没尝试过不知道会不会违和
